import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {Table,seeded} from '../src/engine.js';
import {readBackup} from '../src/backup.js';
const base=process.env.TEST_URL||'http://127.0.0.1:4173';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:process.env.CI?undefined:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const check=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
const t=new Table({rng:seeded(57)});t.start();while(t.s.actor!==0&&!t.s.over)t.act(t.s.actor,t.legal().call?'call':'check');t.s.handId='features-fixture';
const fixture={progress:{xp:125,hands:4,wins:1,trophies:0,onboarded:true,lessons:[],answers:{q2:{attempts:1,correct:1,mastered:true,dueAt:Date.now()-1000,recallLevel:1}},missed:[],daily:{},history:[],reviewed:[],settings:{sound:false,volume:35,hints:true,fourColor:true,speed:'fast',difficulty:'standard'}},table:t.s,notes:[]};
const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('holdem-dojo-v3')));
try{
 await page.addInitScript(data=>{if(!localStorage.getItem('features-seeded')){localStorage.setItem('holdem-dojo-v3',JSON.stringify(data));localStorage.setItem('features-seeded','yes');}const C=window.AudioContext;window.__soundStarts=0;C.prototype._dojoOriginalOscillator=C.prototype.createOscillator;C.prototype.createOscillator=function(){const o=this._dojoOriginalOscillator();const start=o.start.bind(o);o.start=(...args)=>{window.__soundStarts++;return start(...args);};return o;};},fixture);
 await page.goto(base);
 await check('sound preview produces real Web Audio nodes, mute and volume persist',async()=>{await page.locator('.top-actions [data-do="settings"]').click();await page.locator('[data-do="sound-preview"]').click();await page.waitForTimeout(900);assert.ok(await page.evaluate(()=>window.__soundStarts>0));await page.locator('#sound-volume').fill('20');assert.equal((await state()).progress.settings.volume,20);await page.locator('[data-setting="sound"]').uncheck();const before=await page.evaluate(()=>window.__soundStarts);await page.keyboard.press('Escape');await page.locator('[data-action="check"],[data-action="call"]').click();await page.waitForTimeout(800);assert.equal(await page.evaluate(()=>window.__soundStarts),before);assert.equal((await state()).progress.settings.sound,false);await page.locator('.mobile-nav [data-nav="learn"]').click();await page.reload();await page.locator('.top-actions [data-do="settings"]').click();assert.equal(await page.locator('#sound-volume').inputValue(),'20');await page.screenshot({path:'artifacts/v31-sound-mobile.png',fullPage:true});await page.keyboard.press('Escape');});
 await check('ten synthesized effects render non-silent, bounded audio',async()=>{const source=(await readFile('src/audio.js','utf8')).replace('export class','class');const wave=await page.evaluate(async src=>{const Audio=new Function(src+';return DojoAudio')(),out=[];for(const kind of ['deal','fold','check','chip','call','raise','turn','correct','win','retry']){const ctx=new OfflineAudioContext(1,44100,44100);new Audio().render(ctx,ctx.destination,kind);const buffer=await ctx.startRendering();let peak=0,energy=0;for(const v of buffer.getChannelData(0)){peak=Math.max(peak,Math.abs(v));energy+=v*v;}out.push({kind,peak,energy});}return out;},source);for(const w of wave){assert.ok(w.energy>.001,w.kind);assert.ok(w.peak<.7,w.kind);}await writeFile('artifacts/audio-signal-checks.json',JSON.stringify(wave,null,2));});
 await check('backup export is restorable and invalid input never replaces progress',async()=>{await page.locator('.top-actions [data-do="settings"]').click();const downloadEvent=page.waitForEvent('download');await page.locator('[data-do="backup"]').click();const d=await downloadEvent;await d.saveAs('artifacts/roundtrip.json');const text=await readFile('artifacts/roundtrip.json','utf8');assert.equal(readBackup(text).progress.xp,(await state()).progress.xp);await page.locator('#backup-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":1}')});await page.waitForTimeout(200);assert.match(await page.locator('#toast').innerText(),/올바른/);assert.equal((await state()).progress.xp,JSON.parse(text).progress.xp);});
 await check('confirmed import preserves cards, exposes recovery, and restores earlier progress',async()=>{const before=await state(),data=JSON.parse(await readFile('artifacts/roundtrip.json','utf8'));data.progress.xp=432;await page.locator('#backup-file').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.locator('[data-do="restore-backup"]').waitFor();assert.equal((await state()).progress.xp,before.progress.xp);await page.locator('[data-do="restore-backup"]').click();assert.equal((await state()).progress.xp,432);assert.deepEqual((await state()).table.players.map(p=>p.cards),data.table.players.map(p=>p.cards));await page.locator('.top-actions [data-do="settings"]').click();await page.locator('[data-do="undo-import"]').click();await page.locator('[data-do="restore-backup"]').click();assert.equal((await state()).progress.xp,before.progress.xp);});
 await check('due recall and weakest-topic practice work through real controls',async()=>{await page.locator('[data-do="due-review"]').click();assert.match(await page.locator('.quiz-card h2').innerText(),/A♠ 2♦/);await page.locator('[data-answer="2"]').click();assert.ok((await state()).progress.answers.q2.dueAt>Date.now());await page.locator('.mobile-nav [data-nav="growth"]').click();await page.locator('[data-topic="드로우"]').click();assert.match(await page.locator('.quiz-top').innerText(),/드로우/);await page.screenshot({path:'artifacts/v31-training-mobile.png',fullPage:true});});
 await check('question sharing copies an exact deep link that opens its question',async()=>{await page.locator('[data-do="daily-quiz"]').click();const text=await page.locator('.quiz-card h2').innerText();await page.evaluate(()=>{Object.defineProperty(navigator,'share',{value:undefined,configurable:true});});await page.locator('[data-do="share-quiz"]').click();const link=await page.evaluate(()=>navigator.clipboard.readText());assert.match(link,/^https:\/\/holdem-brown\.vercel\.app\/#quiz=q\d+$/);await page.goto(base+'/'+new URL(link).hash);assert.equal(await page.locator('.quiz-card h2').innerText(),text);});
 await check('static guide and privacy are readable on narrow screens and offline',async()=>{await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await context.setOffline(true);for(const route of ['guide.html','privacy.html']){await page.goto(base+'/'+route);assert.equal(await page.locator('a[href="tel:01075295945"]').count()>0,true);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok((await page.locator('h1').innerText()).length>3);}await context.setOffline(false);});
 assert.deepEqual(errors,[]);await writeFile('artifacts/v31-results.json',JSON.stringify({checks,errors},null,2));
}catch(e){await page.screenshot({path:'artifacts/v31-failure.png',fullPage:true});throw e;}finally{await browser.close();}
