import test from 'node:test';
import assert from 'node:assert/strict';
import {QUESTIONS,LESSONS} from '../src/content.js';
import {parseCards,Table,seeded} from '../src/engine.js';
import {updateRecall,dueQuestions,topicStats} from '../src/learning.js';
import {readBackup} from '../src/backup.js';
test('all 36 curated questions have unique IDs, valid cards and explanations',()=>{assert.equal(QUESTIONS.length,36);assert.equal(new Set(QUESTIONS.map(q=>q.id)).size,36);for(const q of QUESTIONS){assert.ok(q.choices[q.answer]);assert.ok(q.why.length>20);const text=[q.cards,q.board].filter(Boolean).join(' '),cards=text?parseCards(text):[];assert.equal(new Set(cards).size,cards.length);}for(const l of LESSONS)assert.ok(QUESTIONS.some(q=>q.id===l.quiz));});
test('recall advances on separate days, becomes due, and resets after error',()=>{const now=new Date(2026,8,10,12).getTime();let a=updateRecall(undefined,true,now);assert.equal(a.dueAt,now+86400000);a=updateRecall(a,true,now+1000);assert.equal(a.recallLevel,1);assert.equal(dueQuestions(QUESTIONS,{q1:a},now).length,0);assert.equal(dueQuestions(QUESTIONS,{q1:a},now+86401000).length,1);a=updateRecall(a,true,now+86401000);assert.equal(a.recallLevel,2);assert.equal(a.dueAt,now+86401000+3*86400000);a=updateRecall(a,false,now+86402000);assert.equal(a.recallLevel,0);assert.equal(a.dueAt,now+86402000+600000);assert.equal(a.mastered,true);assert.equal(topicStats(QUESTIONS,{q1:a})[0].name,'기초');});
function fixture(){const table=new Table({rng:seeded(42)});table.start();table.s.handId='backup-fixture';return {version:3,progress:{xp:10,hands:1,wins:0,trophies:0,lessons:[],missed:[],answers:{},reviewed:[],history:[],daily:{},settings:{sound:false,hints:true,fourColor:true,speed:'normal',difficulty:'standard'}},table:table.s,notes:[]};}
test('v3.0 backup restores current hand without losing chips or legacy settings',()=>{const b=fixture(),r=readBackup(JSON.stringify(b));assert.deepEqual(r.table.players.map(p=>p.cards),b.table.players.map(p=>p.cards));assert.equal(r.table.pot,b.table.pot);assert.equal(r.progress.settings.sound,false);assert.equal(r.progress.reviewsCompleted,0);});
test('backup rejects malformed data and injected presentation attributes',()=>{for(const edit of [b=>b.progress.xp=-1,b=>b.table.deck.push(b.table.deck[0]),b=>b.progress.history.push({id:'broken'}),b=>b.progress.answers.q1={attempts:1,correct:2},b=>b.table.handId='\" onclick=evil',b=>b.table.players[0].name='<img src=x onerror=evil>']){const b=fixture();edit(b);assert.throws(()=>readBackup(JSON.stringify(b)));}assert.throws(()=>readBackup('{"version":3,"__proto__":{}}'));assert.throws(()=>readBackup('x'.repeat(5*1024*1024+1)));const b=fixture();b.table.players[1].color='\" onclick=evil';const r=readBackup(JSON.stringify(b));assert.doesNotMatch(r.table.players[1].color,/onclick/);});
test('completed hand backup retains a renderable, reconstructed result',()=>{const b=fixture(),t=Table.restore(b.table);while(!t.s.over){if(t.s.actor<0)t.advance();else t.act(t.s.actor,t.legal().call?'call':'check');}b.table=t.s;const r=readBackup(JSON.stringify(b));assert.deepEqual(r.table.result.won,t.s.result.won);assert.equal(r.table.result.totalPot,t.s.result.totalPot);});
